#pragma once

#ifdef AUDIO_ENABLE
    //#define STARTUP_SONG SONG(PREONIC_SOUND)
    #define DEFAULT_LAYER_SONGS { \
        SONG(COLEMAK_SOUND), \
        SONG(QWERTY_SOUND), \
        SONG(DVORAK_SOUND) \
    }
#endif

#define NO_MUSIC_MODE

#define FORCE_NKRO

#undef RGBLIGHT_ANIMATIONS
// #undef RGBLIGHT_EFFECT_ALTERNATING
// #undef RGBLIGHT_EFFECT_BREATHING
// #undef RGBLIGHT_EFFECT_CHRISTMAS
// #undef RGBLIGHT_EFFECT_KNIGHT
// #undef RGBLIGHT_EFFECT_SNAKE
// #undef RGBLIGHT_EFFECT_STATIC_GRADIENT
// #undef RGBLIGHT_EFFECT_TWINKLE

// #undef RGBLIGHT_EFFECT_RAINBOW_MOOD
// #undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
// #undef RGBLIGHT_EFFECT_RGB_TEST
