#pragma once

#define STARTUP_SONG SONG(PREONIC_SOUND)
#define DEFAULT_LAYER_SONGS { \
    SONG(COLEMAK_SOUND), \
    SONG(QWERTY_SOUND), \
    SONG(DVORAK_SOUND) \
}

#define NO_MUSIC_MODE
#define FORCE_NKRO

#undef USE_CIE1931_CURVE
#undef RGBLIGHT_ANIMATIONS

#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST

/* 16 ticks, wrap around */
#define RGBLIGHT_HUE_STEP 16
#define RGBLIGHT_DEFAULT_HUE 16

/* 51 102 153 204 255 */
#define RGBLIGHT_SAT_STEP 51
#define RGBLIGHT_DEFAULT_SAT 255

/* 51 102 153 204 255 */
#define RGBLIGHT_VAL_STEP 51
#define RGBLIGHT_DEFAULT_VAL 153

#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL
