SRC += muse.c

BOOTMAGIC_ENABLE = lite
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
DIP_SWITCH_ENABLE = no
EEPROM_DRIVER = transient
ENCODER_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
